---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: spark-genai-devkit
description: This is a distribution based on the latest bluefin image, designed for GenAI development.

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: stable

modules:
  - type: rpm-ostree
    install:
      - alacritty
      - lastpass-cli
      - glances
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

